### ISSUE TITLE
sliced tables import

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-snowflake#15]
Pokud stahuju nějakou větší tabulku, tohle je výstup jedný query extraktoru

```
$ ls -la data/out/tables
total 187184
drwxr-xr-x 2 ondra apache     4096 May 26 09:52 .
drwxr-xr-x 3 ondra apache     4096 May 26 09:48 ..
-rw-r--r-- 1 root  root   21783854 May 26 09:52 in_c-snowflake-test_rfm_0_0_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_0_0.csv.gz.manifest
-rw-r--r-- 1 root  root   23982716 May 26 09:51 in_c-snowflake-test_rfm_0_1_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_1_0.csv.gz.manifest
-rw-r--r-- 1 root  root   20432676 May 26 09:52 in_c-snowflake-test_rfm_0_2_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_2_0.csv.gz.manifest
-rw-r--r-- 1 root  root   25430284 May 26 09:51 in_c-snowflake-test_rfm_0_3_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_3_0.csv.gz.manifest
-rw-r--r-- 1 root  root   26020504 May 26 09:51 in_c-snowflake-test_rfm_0_4_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_4_0.csv.gz.manifest
-rw-r--r-- 1 root  root   24612172 May 26 09:51 in_c-snowflake-test_rfm_0_5_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_5_0.csv.gz.manifest
-rw-r--r-- 1 root  root   26030043 May 26 09:51 in_c-snowflake-test_rfm_0_6_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_6_0.csv.gz.manifest
-rw-r--r-- 1 root  root   23297514 May 26 09:51 in_c-snowflake-test_rfm_0_7_0.csv.gz
-rw-r--r-- 1 root  root        104 May 26 09:52 in_c-snowflake-test_rfm_0_7_0.csv.gz.manifest
```

Manifesty jsou všechny stejný a je v nich
```
destination: in.c-snowflake-test.rfm
delimiter: ','
enclosure: '"'
primary_key: {  }
incremental: false
```

Takže se do obsahu tabulky zapíše pouze poslední uploadovanej slice.

**Comment by ondrejhlavacek** [comment]
Imho to bude chtít použít slicovaný soubory - https://developers.keboola.com/extend/common-interface/folders/#sliced-tables. Stačí 

- v COOPY commandu změnit `HEADER = true` na `HEADER = false`
- soubory ze stagingu nahrát do subfolderu
- vytvořit manifest k tomu subfolderu 
- do manifestu vložit názvy sloupců (z metadat tabulky)

**Comment by ondrejhlavacek** [comment]
Table columns example:

https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Backend/Snowflake.php#L482

**Comment by ondrejhlavacek** [comment]
I'd use sliced files even if there's only one slice in Snowflake S3 staging. It will make it simple.

**Comment by ondrejhlavacek** [comment]
This method - https://github.com/keboola/db-extractor-snowflake/blob/61eed2cc83f0686bd03b6bc81f8dc347ad71b871/tests/Keboola/Extractor/SnowflakeTest.php#L187 should also validate `columns` prop in output table manifest

**Comment by ondrejhlavacek** [comment]
I'll just store here my temp config I used to test the output of the container. I prepped the db in a Snowflake writer. I'll run this again after the image is in quay before updating the app definition. 

```
---
parameters:
  db:
    port: 443
    ssh:
      sshPort: 22
    host: keboola.snowflakecomputing.com
    user: sapi_workspace_212751
    "#password": ***
    database: sapi_232
    schema: workspace_212751
    warehouse: KEBOOLA_PROD
  tables:
  - id: 98845
    enabled: true
    query: SELECT * FROM "rfm-cdai_competition";
    name: rfm-cdai_competition
    primaryKey: []
    incremental: false
    outputTable: in.c-snowflake-test.rfm
```
